from sklearn.cluster import KMeans


def cluster_embeddings(embeddings, n_clusters: int = 4):
    """Cluster customer embeddings with K-Means.

    Args:
        embeddings: Numeric embedding matrix generated by the neural model.
        n_clusters: Number of embedding clusters to produce.

    Returns:
        Cluster labels for each embedding row.
    """
    kmeans = KMeans(
        n_clusters=n_clusters,
        random_state=42,
        n_init=10
    )
    labels = kmeans.fit_predict(embeddings)

    return labels
