from pathlib import Path

import matplotlib.pyplot as plt
from sklearn.manifold import TSNE


def visualize_embedding_clusters(
    embeddings,
    labels
):
    """Create and save a t-SNE plot of clustered customer embeddings.

    Args:
        embeddings: Numeric embedding matrix generated by the neural model.
        labels: Cluster label for each embedding row.

    Returns:
        None.
    """
    tsne = TSNE(
        n_components=2,
        random_state=42,
        perplexity=30
    )
    reduced_embeddings = tsne.fit_transform(
        embeddings
    )

    plt.figure(figsize=(10, 7))
    scatter = plt.scatter(
        reduced_embeddings[:, 0],
        reduced_embeddings[:, 1],
        c=labels
    )
    plt.title(
        "t-SNE Visualization of Customer Embeddings"
    )
    plt.xlabel("t-SNE Component 1")
    plt.ylabel("t-SNE Component 2")
    plt.colorbar(scatter)

    plot_dir = Path("outputs/plots")

    plot_dir.mkdir(
        parents=True,
        exist_ok=True
    )
    plt.savefig(
        plot_dir / "embedding_tsne.png"
    )
    plt.close()
